Cart.create!([
  {user_id: 4},
  {user_id: 2},
  {user_id: 9},
  {user_id: 1},
  {user_id: 5},
  {user_id: 7},
  {user_id: 31},
  {user_id: 25},
  {user_id: 32}
])
Comment.create!([
  {body: "Claro eos amor.", item_id: 5},
  {body: "Sapiente consequuntur cresco desipio et.", item_id: 2},
  {body: "Torrens uredo synagoga torqueo illo aranea sperno.", item_id: 2},
  {body: "Cogo caput comminor conscendo civis vito venia amor.", item_id: 10},
  {body: "Verto amor video eligendi eveniet vulgaris libero.", item_id: 7},
  {body: "Adfero viriliter molestiae nisi vulticulus quasi saepe enim.", item_id: 2},
  {body: "Creator subseco vacuus cultura adsidue uberrime.", item_id: 4},
  {body: "Carmen vehemens casus cernuus.", item_id: 3},
  {body: "Condico utique comminor.", item_id: 6},
  {body: "Speciosus delinquo voluptatibus admoveo natus tyrannus.", item_id: 9},
  {body: "Vindico distinctio tres cornu ipsam recusandae ventosus sum.", item_id: 3},
  {body: "Cernuus unde pel avarus.", item_id: 2},
  {body: "Urbs artificiose velit compello.", item_id: 6},
  {body: "Attollo ut et theca beneficium cunae.", item_id: 5},
  {body: "Texo dens assentator vulgivagus delinquo vero.", item_id: 8},
  {body: "Cura comptus decerno corona.", item_id: 5},
  {body: "Fuga corrigo aegre tumultus crux alioqui celo tego.", item_id: 7},
  {body: "Annus adversus aegre votum aestus cruciamentum tenus.", item_id: 2},
  {body: "Termes labore unde vir confugo viriliter.", item_id: 8},
  {body: "Advoco adopto vultuosus non.", item_id: 8},
  {body: "Umerus attonbitus vinitor vita ultio averto addo asporto.", item_id: 9},
  {body: "Deporto truculenter arbitro autus peccatus tergeo.", item_id: 9},
  {body: "Ex vomito acsi umbra.", item_id: 5},
  {body: "Spectaculum acquiro ter tollo sumptus corpus.", item_id: 10},
  {body: "Ut ullam quos cura candidus.", item_id: 9},
  {body: "Eaque adversus civitas.", item_id: 5},
  {body: "Sono convoco iusto contabesco capio textilis.", item_id: 4},
  {body: "Antea cunabula quia trans.", item_id: 9},
  {body: "Triumphus hic barba.", item_id: 1},
  {body: "Aestus decumbo cribro.", item_id: 4},
  {body: "Timor celebrer deorsum adipiscor adflicto aut barba.", item_id: 7},
  {body: "Corpus talio aut.", item_id: 9},
  {body: "Et defaeco velut expedita cuius unde.", item_id: 4},
  {body: "Cavus vomer viduo verus thorax dolores avaritia trucido.", item_id: 8},
  {body: "Aeneus sono curvus terror timidus aut.", item_id: 3},
  {body: "Eum consequuntur eos.", item_id: 7},
  {body: "Distinctio debeo turbo voluptatum tremo accendo.", item_id: 1},
  {body: "Autem ut demitto nulla.", item_id: 1},
  {body: "Venia aureus iure itaque contabesco.", item_id: 9},
  {body: "Neque turba commodi depromo trepide.", item_id: 3},
  {body: "Reprehenderit arto termes depromo cum turba corrupti quaerat.", item_id: 5},
  {body: "Sit tergum canis.", item_id: 9},
  {body: "Aufero non urbanus cibo est claro sophismata antea.", item_id: 10},
  {body: "Sint quos tero creptio aggredior.", item_id: 10},
  {body: "Cupio compello derideo tollo confero conor quis adinventitias.", item_id: 4},
  {body: "Blandior tyrannus victus.", item_id: 4},
  {body: "Decor est sunt depraedor.", item_id: 7},
  {body: "Sub defendo ascit.", item_id: 3},
  {body: "Clibanus decretum tricesimus atrocitas.", item_id: 9},
  {body: "Tabgo corrumpo aspicio.", item_id: 3}
])
Item.create!([
  {name: "Zamit", description: "[\"Voluptas qui ad velit ipsa perspiciatis omnis nisi. Ut unde provident id ratione dolor. Dolor eius earum nemo consequatur. Aut ullam ut quo.\"]", price: 17.43},
  {name: "Stim", description: "[\"Deleniti et illo expedita omnis iure. Blanditiis ea incidunt dignissimos aspernatur nemo. Dolorem sint repellat reprehenderit sed.\"]", price: 92.09},
  {name: "Toughjoyfax", description: "[\"Sit quasi dolorem alias eligendi. Similique accusantium recusandae possimus. Eius necessitatibus animi aut maiores omnis sit odio. Est eum accusamus itaque et.\"]", price: 69.9},
  {name: "Vagram", description: "[\"Magnam reiciendis esse occaecati amet. Est est sint minima maiores voluptatem. Impedit et ex.\"]", price: 54.16},
  {name: "Viva", description: "[\"Id vel tenetur. Quo qui quos iste minus dolore officia neque. Nostrum consequatur vitae dolorem occaecati rerum commodi voluptas. Iste molestiae fuga dolores est labore minima. Fuga suscipit vero inventore ut quibusdam ipsa veritatis.\"]", price: 65.26},
  {name: "Sonsing", description: "[\"Dolor et repellendus. Facere quisquam pariatur sed dolor placeat. Ad voluptas modi incidunt et quis fuga et. Labore quas tempore. Est sapiente possimus.\"]", price: 27.22},
  {name: "Domainer", description: "[\"Voluptas sed aut. Quia est harum. Rem praesentium et. Quia qui sit. Eum quia quia.\"]", price: 37.12},
  {name: "Ronstring", description: "[\"Sunt quia fuga dolor saepe itaque. Adipisci repellendus neque. Enim autem itaque. Dolorem magni voluptate doloremque maxime sequi.\"]", price: 50.63},
  {name: "Solarbreeze", description: "[\"Quo est voluptas veritatis minima cumque aliquam. Dolor et ut unde. Tempora ipsam corrupti quod dolores alias et dignissimos.\"]", price: 98.0},
  {name: "Flexidy", description: "[\"Doloribus praesentium rerum hic. Et eos debitis. Et cum ex est ut culpa. Repudiandae voluptatem nulla non sequi enim maxime. Et et repudiandae dolor sunt molestiae.\"]", price: 53.81},
  {name: "Sony Vegas", description: "professional program for mounting video", price: 40.0}
])
Position.create!([
  {cart_id: 9, item_id: 9, quantity: nil},
  {cart_id: 8, item_id: 8, quantity: nil},
  {cart_id: 7, item_id: 7, quantity: nil},
  {cart_id: 6, item_id: 6, quantity: nil},
  {cart_id: 5, item_id: 5, quantity: nil},
  {cart_id: 4, item_id: 4, quantity: nil},
  {cart_id: 3, item_id: 3, quantity: nil},
  {cart_id: 1, item_id: 2, quantity: nil},
  {cart_id: 2, item_id: 1, quantity: nil}
])
User.create!([
  {email: "mary.christiansen@gmail.com", password_digest: "$2a$10$CaiTerb1OrnldTVtiK9IHev5/UC/B.2sqxGXqh.Uan018YvJ2UMrC", first_name: "Jasper", last_name: "Cassin", phone_number: "+380876229320", city: "East Leon"},
  {email: "sherman_hettinger@hotmail.com", password_digest: "$2a$10$rWlOUEGPdzB7ssO95pxRCO56ZPumOMudqs9XN/lOCqiCJDxN2nTUe", first_name: "Yasmine", last_name: "Monahan", phone_number: "+380475443066", city: "Simstad"},
  {email: "johnnie@yahoo.com", password_digest: "$2a$10$PbY68b5mkJlxMzmPYVYEDeLkd5ivxHvOEcL2EFvKyA8jSoixkzMPe", first_name: "Aisha", last_name: "Frami", phone_number: "+380999261266", city: "Jenkinshaven"},
  {email: "emmalee@gmail.com", password_digest: "$2a$10$6cvxZMWHC7VZNzhxu2Bt.ON6BfLHene9JQai/8b6hnlSDAaanGpK6", first_name: "Lenny", last_name: "Walker", phone_number: "+380138211638", city: "Dexterchester"},
  {email: "noemie.cummerata@yahoo.com", password_digest: "$2a$10$ATKRw9Ps3nKiS8lI8twHm.UL7NSlR9FOFll1uidI0qxEOwnBfyjLS", first_name: "Jayme", last_name: "Wiegand", phone_number: "+380464331144", city: "Ilianaland"},
  {email: "immanuel_sawayn@hotmail.com", password_digest: "$2a$10$kKYXKN5lf3UCEkehwnSHhu2YMVyHMUe1xax5FoVY7NHv/z404goSO", first_name: "Macie", last_name: "Turner", phone_number: "+380564745208", city: "East Karleemouth"},
  {email: "abigale.shanahan@hotmail.com", password_digest: "$2a$10$9pxN.S7pmAuJ9U911wXHu.whyc4Ls3Vn8eEiIi8vgDj8MU8nfteaa", first_name: "Zachery", last_name: "Gibson", phone_number: "+380539216835", city: "Billyfort"},
  {email: "kathryne@hotmail.com", password_digest: "$2a$10$WYp8AYWmul7a3RscaIQ4FuI9t3SE6ljcqDxCoz9hialUzUEQsfXNq", first_name: "Marion", last_name: "Ryan", phone_number: "+380922779975", city: "North Olafstad"},
  {email: "cathy@gmail.com", password_digest: "$2a$10$r02gdc2TuzftVtzXRQhZSe4ilp7mJKLPm5a4YKKGSrFCg5U4s.sLa", first_name: "Jacques", last_name: "Kerluke", phone_number: "+380900029754", city: "Montefurt"},
  {email: "rusty.mante@yahoo.com", password_digest: "$2a$10$GLZCjPD9eUtw6Q6QHuMLAen9x.J3KQbO5QptCfVyd4K5DRCPnfF12", first_name: "Torey", last_name: "King", phone_number: "+380724681846", city: "Port Teresa"},
  {email: "columbus.grant@gmail.com", password_digest: "$2a$10$xYzkmzu.7AhhS577SP20neHp0fXhzbzdow1eKaKqSmbZm5ngeR0NS", first_name: "Celestine", last_name: "Marks", phone_number: "+380270352859", city: "East Edmund"},
  {email: "brandyn_pacocha@gmail.com", password_digest: "$2a$10$IFiHIeApnT894rMUHsptSusnsZPuxzDlZtuxaw3.EhBu6hvwHYGsS", first_name: "Henderson", last_name: "White", phone_number: "+380472624112", city: "Dustystad"},
  {email: "grace@gmail.com", password_digest: "$2a$10$9jm.QzGSVKX6EDz7qT2fh.cINjpk1DNI2y9mXNgABJGYx6C0xyKlG", first_name: "Buddy", last_name: "Stoltenberg", phone_number: "+380297401217", city: "Port Mathew"},
  {email: "newton@yahoo.com", password_digest: "$2a$10$pzALp1ePl8fG/hGd7pt8Lu31FKKwkZCflukBmu6qZ3HIGJTbPVtr2", first_name: "Lyda", last_name: "Aufderhar", phone_number: "+380809468730", city: "Langoshland"},
  {email: "eric@hotmail.com", password_digest: "$2a$10$ENUbq5BBx0R99a/i7vj0XONC8xYDYQ5Bg7Xx18L4VRhtK9liT9QpO", first_name: "Cassidy", last_name: "Stoltenberg", phone_number: "+380742651404", city: "Hegmannton"},
  {email: "elwyn_robel@yahoo.com", password_digest: "$2a$10$/Vfw6pTVCzX725s9v5y0vu/S6qIUyeOBbjL8/MKwhHIEDwItZUWLi", first_name: "Nia", last_name: "Runolfsson", phone_number: "+380248607170", city: "Lake Barney"},
  {email: "lyric@yahoo.com", password_digest: "$2a$10$5pFxsJs.f74w9d5lBBeuiOgSb8/cOQ2mHBlCm6YzfTRRmlGNkkp1O", first_name: "Janelle", last_name: "Hamill", phone_number: "+380443543569", city: "Eulaliaberg"},
  {email: "lance@gmail.com", password_digest: "$2a$10$McC.ej0V/NhTthUlBYIZguR8ubK29lh1pbEq/OmgigLZGgmFh0jt2", first_name: "Eden", last_name: "Aufderhar", phone_number: "+380241347176", city: "Collierfort"},
  {email: "lavonne@hotmail.com", password_digest: "$2a$10$Ryvpwfqyx8a3AzzjcZMQDO.slrIc3KNEPWk8yusyJHTd6Wr0ZhSlq", first_name: "Anne", last_name: "Harris", phone_number: "+380979564579", city: "South Destany"},
  {email: "frederick_cummings@yahoo.com", password_digest: "$2a$10$NXa9JqddoRHKgWxv59Hid.c98pWzY7Y0yYOPuQoTiCt5PuKTUsay.", first_name: "Lorenza", last_name: "Graham", phone_number: "+380604696471", city: "Port Shane"},
  {email: "holly.bosco@hotmail.com", password_digest: "$2a$10$yxKalLCkbiwXzvFEqRtiAen6DA5uSoxHlYc.JQS5Ttjh3lA6eHVUG", first_name: "Noe", last_name: "Daugherty", phone_number: "+380272461255", city: "Gerlachhaven"},
  {email: "jenifer@yahoo.com", password_digest: "$2a$10$JBkLneEFCa2sr5czIBr2QeWtfGYLfQgWhboCF9ewebfdlAvKKkuR.", first_name: "Julio", last_name: "Beatty", phone_number: "+380832365541", city: "East Beulahberg"},
  {email: "abdullah_bode@yahoo.com", password_digest: "$2a$10$YJok2chmZYeXpxyKPeMjMegKdZmYwHLskUqytOdjd2Groio0B5Ssi", first_name: "Eddie", last_name: "Sipes", phone_number: "+380372921937", city: "South Frederick"},
  {email: "esperanza@yahoo.com", password_digest: "$2a$10$CabNpXpC7oRVEgXP6rS3/uK97jGtv.xI/kGnh62EXKLoXbij8YYI.", first_name: "Magdalena", last_name: "Reynolds", phone_number: "+380683017003", city: "East Betty"},
  {email: "flavie@gmail.com", password_digest: "$2a$10$sjQ/W5DikursaDXRcxUIPeCWA8H8s/YoQZSSWXSJzqwn9Rmfetq4q", first_name: "Luigi", last_name: "Wilkinson", phone_number: "+380634899444", city: "South Myah"},
  {email: "scarlett@hotmail.com", password_digest: "$2a$10$auv6L4jjMvGQQH1.eclgg.dmT3ZNeB9YE.5RZLE/C7yjcwAp3MMFu", first_name: "Jonas", last_name: "Wuckert", phone_number: "+380673243976", city: "Lake Alexanneport"},
  {email: "kameron@hotmail.com", password_digest: "$2a$10$417O2.A1GPwLp2kQrfK8jevOuQxuboLuTQG8KBzAElEB7cTEpiHxC", first_name: "Otis", last_name: "O'Reilly", phone_number: "+380233583913", city: "Lake Ova"},
  {email: "kirk.maggio@gmail.com", password_digest: "$2a$10$ueIaFeKUPPo0gfihHvQqLOA8/O0NVmdCPVdi94Bqf77ppgvdigjG.", first_name: "Kadin", last_name: "Goldner", phone_number: "+380627409677", city: "Lake Fredrickhaven"},
  {email: "emmett.gutkowski@gmail.com", password_digest: "$2a$10$MGVhe7NyiWyDFt38fKQB3OrVuWCjT65oOtj7efsIO5qgb0O97M6uu", first_name: "Bridie", last_name: "VonRueden", phone_number: "+380674578450", city: "Lake Ellaview"},
  {email: "elmo.cain@hotmail.com", password_digest: "$2a$10$njgft0AUVWeszv17Jag06O8BZt6x7rVh/56wYAHLWc0mnloOjt64m", first_name: "Timothy", last_name: "Hintz", phone_number: "+380707555852", city: "New Karleebury"},
  {email: "keyshawn@yahoo.com", password_digest: "$2a$10$pOLM62mFLQD.2KnkI6WRougMJq7GLOZ7R.h9omhpLR2jQke/D5cla", first_name: "Conner", last_name: "Schaefer", phone_number: "+380770365976", city: "West Elyse"},
  {email: "willa@yahoo.com", password_digest: "$2a$10$0adaIyu24kB7dn3fbtD1geHPSWnX4HxRxIYrzHHFqHNHIdHANxZKC", first_name: "Lia", last_name: "Harvey", phone_number: "+380882705633", city: "Connorstad"},
  {email: "scarlett@yahoo.com", password_digest: "$2a$10$hueXoXmOBQpLF4Bb144/LupozqshSVPFSmTFTC.MtfqDaBUirIW0q", first_name: "Ilene", last_name: "Nienow", phone_number: "+380881167379", city: "West Cleveland"},
  {email: "priscilla.lang@hotmail.com", password_digest: "$2a$10$3NBeQuje4B0efhJLo2ZGwe1ianKOZtWHhm7t351tfAwhrVmFRwfm2", first_name: "Kaela", last_name: "Kemmer", phone_number: "+380726002955", city: "South Jermey"},
  {email: "loyce_steuber@gmail.com", password_digest: "$2a$10$9uCuFKRfbN7o3dvbHvLFw.f0kdZnHrl//IvhDw4t3Sl8COgHdhOoC", first_name: "Peter", last_name: "Bahringer", phone_number: "+380756879942", city: "Lake Greyson"},
  {email: "tremayne@hotmail.com", password_digest: "$2a$10$EIqaNvmcMyHxS019xps77uDS1moomsRd7BixTmUgMCCW4A1dzVM9a", first_name: "Doyle", last_name: "Stanton", phone_number: "+380447082037", city: "West Eladioberg"},
  {email: "daniella_brakus@gmail.com", password_digest: "$2a$10$TziX3XcFI5AuSKKNNvHOc.jK6yzEEb8qSwiTcrEdMcaOTRLIrZ/7C", first_name: "Lilly", last_name: "Beier", phone_number: "+380484187564", city: "Lake Jovanny"},
  {email: "arlo.wehner@gmail.com", password_digest: "$2a$10$XaQ8xc6lLsOO0qbXnUciHuo8bytRYZp.URluV9PCShb.uy5L.C9tW", first_name: "Destany", last_name: "Tremblay", phone_number: "+380958495992", city: "Albertland"},
  {email: "mose_stamm@yahoo.com", password_digest: "$2a$10$ZbzX7WUZW3SwR71ucuk41eb1jJQg7yAyOCbFKPszoPdWr25vTCWUG", first_name: "Blaze", last_name: "Schultz", phone_number: "+380836125748", city: "Nicholeport"},
  {email: "bradley@yahoo.com", password_digest: "$2a$10$yX4t0O9i44p/A249N5AMheZCAaJElsfTmbSryAikD1o1WLlpfNA32", first_name: "Lilla", last_name: "Wiegand", phone_number: "+380523987686", city: "West Kaya"},
  {email: "virginia.stehr@yahoo.com", password_digest: "$2a$10$cSYs86q9aIGeRCDHKcVOxO5LCbHn0UeK6iMMELWCTWXCzeRLSx26S", first_name: "Ross", last_name: "Zulauf", phone_number: "+380171047745", city: "East Annabell"},
  {email: "jevon_bosco@yahoo.com", password_digest: "$2a$10$MMc1xE1JA38VgqIV81eA/uC.kYlAlko9mpC8xAwHubMMA3.vJpDzi", first_name: "Leonard", last_name: "Greenfelder", phone_number: "+380333936814", city: "East Shanie"},
  {email: "miguel@gmail.com", password_digest: "$2a$10$MN9Dqx3ufKQZpxZAVKkDJ.U7SLJCnKVug60Xz6eHpXuuGXusLVF1a", first_name: "Kiara", last_name: "Pacocha", phone_number: "+380780989677", city: "Leannonside"},
  {email: "madyson@hotmail.com", password_digest: "$2a$10$aZidklfaHqDtcgK7bdGW5OaeBzN6OG.7sxHDgwE7fBDBuRZrAEv4e", first_name: "Maximilian", last_name: "Jacobi", phone_number: "+380179579650", city: "New Alessiaville"},
  {email: "deborah_langosh@hotmail.com", password_digest: "$2a$10$n4sWn0sh6g9ZfZYqFEZM8Oh80aVo6t0xO8I3S9apQT.O3a4IeBR7G", first_name: "Napoleon", last_name: "Dickinson", phone_number: "+380519895967", city: "North Gloria"},
  {email: "napoleon@gmail.com", password_digest: "$2a$10$POP/h3br4D0ZVfOsM0Sh4e72qk/CiDebaizkQ5KRZCdd3kMPppfwK", first_name: "Leonor", last_name: "Medhurst", phone_number: "+380744632156", city: "Keeblerborough"},
  {email: "ebony@hotmail.com", password_digest: "$2a$10$M.UDzGOzyU.1Qw/pcScwEua8QMos04eV67ej7rZNSFnOWIVljpLiu", first_name: "Tanya", last_name: "Abshire", phone_number: "+380764742901", city: "Coralieshire"},
  {email: "salma_cartwright@yahoo.com", password_digest: "$2a$10$LWuKOYdUo3BW.lPL5h6toeF5dcy8necHSKWSA1xpz7M5v2luI2IGS", first_name: "Anais", last_name: "Bode", phone_number: "+380697226515", city: "South Richard"}
])
